### ISSUE TITLE
General Questions / Comments

### ISSUE THREAD

**Issue by Shushman** [joanathan/social_distancing_density#1]
I stumbled upon this through the Lacuna blog and thought it was an interesting starting point, great work!

1. In point 6, when you discuss the percentage of people walking on the street - does that mean you assume that x% of the census block population is walking on each sidewalk in the block at the same time? If not, how do you divide up the population of the census block over the different sidewalks within the block? More generally, I wonder if aggregate mobility data from SafeGraph or others could be used to simulate finer resolution movement patterns.

2. Many South Bay Area cities have closed down certain roads to allow restaurants to spill over and more walking room for residents (hopefully that change stays after the vaccine!). I assume the road closure decisions were made based on some heuristic by city officials. It would be interesting to frame the problem of which streets to close to best tradeoff social distancing vs traffic (e.g., the fewest street closures that would achieve x% more social distancing density).

Anyway, cheers!

**Comment by joanathan** [comment]
Thanks, @Shushman!  

The analysis assumes that x% of the block group population is walking on each sidewalk in their home block group simultaneously. It’s a crude assumption — Most people are not going to walk/stay only in their home block group nor at the same time. I had considered an improvement to distribute the population to walk to other block groups based on their trip purpose, i.e., walk from home to grocery stores.

This project was done using free open data. To your point, absolutely — having access to data like one from Safegraph, @foursquare, or others will help refine the analysis. Tagging @SafeGraphInc in case they offer any free data for any social distancing/COVID related research. 

Yes — Palo Alto closes University St for restaurant spillover and more walking room, which I hope it stays that way even after SIP is lifted.

**Comment by Shushman** [comment]
Makes sense! Thanks for clarifying.
